# Generated by Django 2.2 on 2019-06-03 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('managejob', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='category',
            field=models.CharField(choices=[('1', 'Web design'), ('2', 'Graphic design'), ('3', 'Web development'), ('4', 'Human Resources'), ('5', 'Support'), ('6', 'Android')], max_length=100),
        ),
    ]
